name: eco-ecotrack-dashboard
services:
  eco-ecotrack-dashboard:
    image: eco-ecotrack-dashboard
    container_name: eco-ecotrack-dashboard
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './eco-ecotrack-dashboard:/usr/src/app'
    ports:
      - 127.0.0.1:4300:80
    networks:
      - devnet

networks:
  devnet:
    external: true
    name: devnet
